// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlyBa8ULJUKI7eJ8YwdlB11C61S3abSjs',
    appId: '1:134439313159:web:7f4a98f08d2012b2ff2fa2',
    messagingSenderId: '134439313159',
    projectId: 'login-testit',
    authDomain: 'login-testit.firebaseapp.com',
    storageBucket: 'login-testit.appspot.com',
    measurementId: 'G-67MKK1DK3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDud2XA3fPX4XSO7uRLc62Wgra45Jy7_LY',
    appId: '1:134439313159:android:dc5f4e7737033674ff2fa2',
    messagingSenderId: '134439313159',
    projectId: 'login-testit',
    storageBucket: 'login-testit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsi3B396BHtIlUC3BDwQpZwtFh5x6t2fg',
    appId: '1:134439313159:ios:45dea4fb2ce1edd7ff2fa2',
    messagingSenderId: '134439313159',
    projectId: 'login-testit',
    storageBucket: 'login-testit.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsi3B396BHtIlUC3BDwQpZwtFh5x6t2fg',
    appId: '1:134439313159:ios:30011631bab7b558ff2fa2',
    messagingSenderId: '134439313159',
    projectId: 'login-testit',
    storageBucket: 'login-testit.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
